export const defaultColumns = [
    { id: "id", label: "#", width: "60px" },
    { id: "saudi_office", label: "المكتب السعودي", width: "150px" },
    { id: "client", label: "المندوب", width: "150px" },
    { id: "visa_holder_name", label: "صاحب التأشيرة", width: "150px" },
    { id: "visa_holder_phone", label: "رقم صاحب التأشيرة", width: "130px" },
    { id: "visa_number", label: "رقم التأشيرة", width: "120px" },
    { id: "service_type", label: "نوع الخدمة", width: "130px" },
    { id: "musaned_contract_number", label: "رقم عقد مساند", width: "140px" },
    { id: "total_price", label: "إجمالي السعر", width: "120px" },
    { id: "musaned_paid", label: "سداد مساند", width: "120px" },
    { id: "price_difference", label: "الرصيد المتبقي", width: "130px" },
    { id: "is_paid_by_office", label: "السداد من المكتب", width: "130px" },
    { id: "status", label: "حالة سداد مساند", width: "150px" },
    { id: "created_at", label: "التاريخ", width: "110px" },
    { id: "actions", label: "الإجراءات", width: "120px" },
];
