export const defaultColumns = [
    { id: "order_number", label: "# الطلب", width: "70px" },
    { id: "visa_holder", label: "صاحب التأشيرة", width: "170px" },
    { id: "id_number", label: "الهوية", width: "80px" },
    { id: "visa_number", label: "التأشيرة", width: "90px" },
    { id: "delegate_phone", label: "رقم المندوب", width: "80px" },
    { id: "passport_number", label: "رقم الجواز", width: "80px" },
    { id: "authorization_number", label: "رقم التفويض", width: "90px" },
    { id: "authentication_number", label: "رقم التوثيق", width: "80px" },
    { id: "authentication_date", label: "تاريخ التوثيق", width: "90px" },
    { id: "certification_date", label: "تاريخ التصديق", width: "90px" },
    { id: "last_action_date", label: "آخر إجراء", width: "100px" },
    { id: "saudi_office", label: "المكتب السعودي", width: "150px" },
    { id: "external_office", label: "المكتب الخارجي", width: "120px" },
    { id: "passport_status", label: "حالة ترشيح الجواز", width: "150px" },
    { id: "transfer_status", label: "حالة التحويل", width: "150px" },
    { id: "authentication_status", label: "حالة التوثيق", width: "150px" },
    { id: "authorization_status", label: "حالة التفويض", width: "150px" },
    { id: "priority_level", label: "درجة الأهمية", width: "150px" },
    { id: "images", label: "الصور", width: "130px" },
    { id: "actions", label: "إجراءات", width: "80px" },
];
