export const trackingColumns = [
  { id: "strip", label: "", width: "5px" },
  { id: "order_number", label: "# الطلب", width: "80px" },
  { id: "visa_holder", label: "صاحب التأشيرة", width: "180px" },
  { id: "visa_number", label: "التأشيرة", width: "100px" },
  { id: "id_number", label: "الهوية", width: "100px" },
  { id: "delegate_phone", label: "رقم المندوب", width: "110px" },
  { id: "passport_number", label: "رقم الجواز", width: "100px" },
  { id: "authorization_number", label: "رقم التفويض", width: "110px" },
  { id: "authentication_number", label: "رقم التوثيق", width: "110px" },
  { id: "authentication_date", label: "تاريخ التوثيق", width: "110px" },
  { id: "certification_date", label: "تاريخ التصديق", width: "110px" },
  { id: "last_action_date", label: "آخر إجراء", width: "110px" },
  { id: "external_office", label: "المكتب الخارجي", width: "140px" },
  { id: "passport_status", label: "حالة ترشيح الجواز", width: "150px" },
  { id: "transfer_status", label: "حالة التحويل", width: "150px" },
  { id: "authentication_status", label: "حالة التوثيق", width: "150px" },
  { id: "authorization_status", label: "حالة التفويض", width: "150px" },
  { id: "priority_level", label: "درجة الأهمية", width: "150px" },
  { id: "attachments", label: "الصور", width: "150px" },
  { id: "actions", label: "إجراءات", width: "100px" },
];
